dist: xenial
# We use the generic language to prevent Travis from overwriting the CC and CXX
# environment variables. See https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux.
language: generic

# Leak Sanitizer crashes if we don't run with root priviliges.
sudo: true

notifications:
  email: false

env: BNL_TIDY=ON

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CC=gcc-5 CXX=g++-5

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env: CC=clang-6.0 CXX=clang++-6.0

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CC=gcc-8 CXX=g++-8

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
      env: CC=clang-8 CXX=clang++-8

    - os: osx
      osx_image: xcode10
      env: CC=clang CXX=clang++ BNL_TIDY=OFF

# Install newer CMake
install:
  # Download CMake manually on MacOS because brew is too slow.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /usr/local;
    else
      brew uninstall cmake;
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Darwin-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /Applications;
      sudo /Applications/CMake.app/Contents/bin/cmake-gui --install;
    fi;
    export PATH=/usr/local/bin:$PATH;

script:
  - cmake
      -B build
      -S .
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DBNL_TEST=ON
      -DBNL_WARNINGS_AS_ERRORS=ON
      -DBNL_TIDY=$BNL_TIDY
      -DBNL_SANITIZERS=ON
      -DBNL_INSTALL=OFF
  - cmake --build build --parallel 2
  - build/test
