dist: xenial
# We use the generic language to prevent Travis from overwriting the CC and CXX
# environment variables. See https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux.
language: generic

# Leak Sanitizer crashes if we don't run with root priviliges.
sudo: true

notifications:
  email: false

matrix:
  fast_finish: true

env: H3C_TIDY=ON

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CC=gcc-4.9 CXX=g++-4.9

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env: CC=clang-3.5 CXX=clang++-3.5

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CC=gcc-8 CXX=g++-8

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
      env: CC=clang-8 CXX=clang++-8

    - os: osx
      env: CC=clang CXX=clang++ H3C_TIDY=OFF

# Install newer CMake
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sSL https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Linux-x86_64.tar.gz -o cmake.tar.gz;
      sudo tar xf cmake.tar.gz --strip 1 -C /usr/local;
    else
      # brew upgrade returns a non-zero error code if the package is already
      # up-to-date. To avoid this we check if the package is out-of-date first.
      if (brew outdated | grep -q cmake); then
        brew upgrade cmake;
      fi;
    fi;
    export PATH=/usr/local/bin:$PATH;

script:
  - cmake
      -B build
      -S .
      -DCMAKE_BUILD_TYPE=Debug
      -DBUILD_SHARED_LIBS=ON
      -DH3C_TEST=ON
      -DH3C_WARNINGS_AS_ERRORS=ON
      -DH3C_TIDY=$H3C_TIDY
      -DH3C_SANITIZERS=ON
  - cmake --build build --parallel 2
  - build/test
