# -m32: See https://gitlab.kitware.com/cmake/cmake/issues/16259.
jobs:
  - template: ci/windows.yml
    parameters:
      name: windows_vs2015_x86_clang_msvc
      image: vs2015-win2012r2
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
        PLATFORM: x86
        CC: clang-cl.exe
        CXX: clang-cl.exe
        CFLAGS: -m32
        CXXFLAGS: -m32

  - template: ci/windows.yml
    parameters:
      name: windows_vs2015_x64_clang_msvc
      image: vs2015-win2012r2
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
        PLATFORM: x64
        CC: clang-cl.exe
        CXX: clang-cl.exe

  - template: ci/windows.yml
    parameters:
      name: windows_vs2017_x86_clang_msvc
      image: vs2017-win2016
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
        PLATFORM: x86
        CC: clang-cl.exe
        CXX: clang-cl.exe
        CFLAGS: -m32
        CXXFLAGS: -m32

  - template: ci/windows.yml
    parameters:
      name: windows_vs2017_x64_clang_msvc
      image: vs2017-win2016
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
        PLATFORM: x64
        CC: clang-cl.exe
        CXX: clang-cl.exe

  - template: ci/windows.yml
    parameters:
      name: windows_vs_2019_x86_clang_msvc
      image: windows-2019
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
        PLATFORM: x86
        CC: clang-cl.exe
        CXX: clang-cl.exe
        CFLAGS: -m32
        CXXFLAGS: -m32

  - template: ci/windows.yml
    parameters:
      name: windows_vs_2019_x64_clang_msvc
      image: windows-2019
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
        PLATFORM: x64
        CC: clang-cl.exe
        CXX: clang-cl.exe

  - template: ci/windows.yml
    parameters:
      name: windows_vs_2019_x86_clang_gnu
      image: windows-2019
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
        PLATFORM: x86
        CC: clang.exe
        CXX: clang++.exe
        CFLAGS: -m32
        CXXFLAGS: -m32

  - template: ci/windows.yml
    parameters:
      name: windows_vs_2019_x64_clang_gnu
      image: windows-2019
      variables:
        VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
        PLATFORM: x64
        CC: clang.exe
        CXX: clang++.exe

  - template: ci/macos.yml
    parameters:
      name: macos_10_13
      image: macOS-10.13

  - template: ci/macos.yml
    parameters:
      name: macos_10_14
      image: macOS-10.14

  - template: ci/linux.yml
    parameters:
      name: linux_gcc_8
      variables:
        PACKAGES: g++-8
        REPOSITORY: ppa:ubuntu-toolchain-r/test
        CC: gcc-8
        CXX: g++-8

  - template: ci/linux.yml
    parameters:
      name: linux_gcc_9
      variables:
        PACKAGES: g++-9
        REPOSITORY: ppa:ubuntu-toolchain-r/test
        CC: gcc-9
        CXX: g++-9

  # Disabled: See .travis.yml
  # - template: ci/linux.yml
  #   parameters:
  #     name: linux_clang_7
  #     variables:
  #       PACKAGES: clang-7 libc++-7-dev libc++abi-7-dev
  #       REPOSITORY: deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main
  #       CC: clang-7
  #       CXX: clang++-7
  #       CXXFLAGS: -stdlib=libc++

  - template: ci/linux.yml
    parameters:
      name: linux_clang_8
      variables:
        PACKAGES: clang-8 libc++-8-dev libc++abi-8-dev
        REPOSITORY: deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main
        CC: clang-8
        CXX: clang++-8
        CXXFLAGS: -stdlib=libc++
