parameters:
  name: ""
  variables: {}

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: "ubuntu-16.04"
    variables:
      ${{ insert }}: ${{ parameters.variables }}
    steps:
      # Install CMake manually because xenial's packaged version is not up-to-date.
      - script: |
          sudo add-apt-repository "$(REPOSITORY)"
          sudo apt-get update
          sudo apt-get install $(PACKAGES)

          curl -sSL https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.tar.gz -o cmake.tar.gz;
          sudo tar xf cmake.tar.gz --strip 1 -C /usr/local;
        displayName: Install

      - script: |
          export PATH=/usr/local/bin:$PATH;
          cmake \
            -B $(Build.SourcesDirectory)/build \
            -S $(Build.SourcesDirectory) \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_SHARED_LIBS=ON \
            -DBNL_TEST=ON \
            -DBNL_WARNINGS_AS_ERRORS=ON \
            -DBNL_SANITIZERS=ON \
            -DBNL_INSTALL=OFF
        displayName: Configure

      - script: |
          export PATH=/usr/local/bin:$PATH;
          cmake --build $(Build.SourcesDirectory)/build --parallel 2
        displayName: Build

      - script: build/test
        displayName: Test
