parameters:
  name: ''
  image: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  # brew upgrade returns a non-zero error code if the package is already
  # up-to-date. To avoid this we check if the package is out-of-date first.
  - script: |
      if (brew outdated | grep -q cmake); then
        brew upgrade cmake;
      fi
    displayName: Install

  - script: |
      cmake \
        -B $(Build.SourcesDirectory)/build \
        -S $(Build.SourcesDirectory) \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_SHARED_LIBS=ON \
        -DBNL_TEST=ON \
        -DBNL_WARNINGS_AS_ERRORS=ON \
        -DBNL_SANITIZERS=ON
    displayName: Configure

  - script: cmake --build $(Build.SourcesDirectory)/build --parallel 2
    displayName: Build

  - script: build/test
    displayName: Test

