parameters:
  name: ''
  image: ''
  variables: {}

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:

  - powershell: |
      # LLVM's (clang-cl) MSBuild integration is outdated so we use Ninja instead.
      iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      scoop install ninja cmake llvm --global
    displayName: Install

    # Azure Pipelines resets environment variables between steps so we have to
    # add the required environment variables at the start of each step.

  - script: |
      set PATH=C:\ProgramData\scoop\shims;%PATH%
      call "$(VCVARSALL)" $(PLATFORM)
      cmake ^
        -B $(Build.SourcesDirectory)\build ^
        -S $(Build.SourcesDirectory) ^
        -G Ninja ^
        -DCMAKE_BUILD_TYPE=Debug ^
        -DBUILD_SHARED_LIBS=ON ^
        -DBNL_TEST=ON ^
        -DBNL_WARNINGS_AS_ERRORS=ON ^
        -DBNL_TIDY=ON
    displayName: Configure

  - script: |
      set PATH=C:\ProgramData\scoop\shims;%PATH%
      call "$(VCVARSALL)" $(PLATFORM)
      cmake --build $(Build.SourcesDirectory)\build --parallel 2
    displayName: Build

  - script: |
      set PATH=$(Build.SourcesDirectory)\build\bin%
      set PATH=$(Build.SourcesDirectory)\build\bnl\core\lib;%PATH%
      set PATH=$(Build.SourcesDirectory)\build\bnl\http3\lib;%PATH%
      set PATH=$(Build.SourcesDirectory)\build\bnl\log\lib;%PATH%
      set PATH=$(Build.SourcesDirectory)\build\bnl\util\lib;%PATH%
      build\test
    displayName: Test
